### ISSUE TITLE
Suggestion: show browser support status from CanIUse

### ISSUE THREAD

**Issue by sw-yx** [luruke/browser-2020#2]
No need to get into browser politics (😅) but it might be helpful to look at a glance and see what devs can do given the constraints they have.

**Comment by luruke** [comment]
Hi @sw-yx ,
thanks!

I thought about it, but i'm not thinking of maintain this list as it will require quite some work.

Meanwhile i'd suggest to check:
https://whatwebcando.today/
https://chromestatus.com/features

**Comment by sw-yx** [comment]
haha, gotcha.
